DROP TABLE Budget;
DROP TABLE `User`;

CREATE TABLE `User` (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL
);
CREATE TABLE Budget (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	budget DECIMAL(12,2) NOT NULL DEFAULT 0,
	`timeStamp` DATETIME NOT NULL,
	user_id BIGINT NOT NULL,
	CONSTRAINT Budget_FK_User FOREIGN KEY (user_id) REFERENCES `User`(id)
);