ALTER TABLE `User` ADD COLUMN startCapital DECIMAL(15,2) NOT NULL DEFAULT 20000000;
ALTER TABLE `User` ADD COLUMN balanceOffset DECIMAL(15,2) NOT NULL DEFAULT 0;
ALTER TABLE `User` ADD COLUMN points BIGINT NOT NULL DEFAULT 0;